In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("C:\\Users\\Admin\\OneDrive\\Документы\\survey_results_public.csv",low_memory=False)
df.head()

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [3]:
df1=pd.read_csv("C:\\Users\\Admin\\OneDrive\\Документы\\survey_results_schema.csv")
df1.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   qid       139 non-null    object
 1   qname     139 non-null    object
 2   question  139 non-null    object
 3   type      139 non-null    object
 4   sub       49 non-null     object
 5   sq_id     49 non-null     float64
dtypes: float64(1), object(5)
memory usage: 6.6+ KB

In [6]:
df_ua = df[df['Country'] == 'Ukraine']

In [7]:
#Tasck 1
total_respondents = df.shape[0]
print(total_respondents)

49191

In [8]:
#Tasck 2
questions = set(df1['qname'])
columns_to_check = list(questions & set(df.columns))
complete_responses = df[columns_to_check].notna().all(axis=1)
total_complete = complete_responses.sum()
print(total_complete)

0

In [9]:
#Tasck 3
mean_exp=df['WorkExp'].mean()
median_exp=df['WorkExp'].median()
mode_exp=df['WorkExp'].mode()[0]

result = pd.DataFrame({
    'Metric': ['Mean', 'Median', 'Mode'],
    'Value': [mean_exp, median_exp, mode_exp]
})
result=result.round(2)
print(result)

   Metric  Value
0    Mean  13.37
1  Median  10.00
2    Mode  10.00

In [10]:
#Tasck 4
df['RemoteWork'].value_counts()
remote_workers = df[df['RemoteWork'] == 'Remote']
total_remote = remote_workers.shape[0]
print(total_remote)

10931

In [11]:
#Tasck 5
python_users = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)
percent_python = python_users.mean() * 100
print(percent_python)

37.53938728629221

In [12]:
#Tasck 6
df['LearnCode'].head()

0    Online Courses or Certification (includes all ...
1    Online Courses or Certification (includes all ...
2    Online Courses or Certification (includes all ...
3    Other online resources (e.g. standard search, ...
4                                                  NaN
Name: LearnCode, dtype: object

In [13]:
df['LearnCode'].value_counts().head()

LearnCode
Other online resources (e.g. standard search, forum, online community);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system)                                        632
Other online resources (e.g. standard search, forum, online community);Technical documentation (is generated for/by the tool or system)                                                                         465
Online Courses or Certification (includes all media types)                                                                                                                                                      405
Other online resources (e.g. standard search, forum, online community);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps    397
AI CodeGen tools or AI-enabled apps                                                                                                                                                                             387
Name: count, dtype: int64

In [14]:
online_learners = df['LearnCode'].str.contains('Online', na=False)
total_online = online_learners.sum()

print(total_online)

10973

In [16]:
#Tasck7
python_df = df[df['LanguageHaveWorkedWith'].str.contains('Python', na=False)]
python_df = python_df[python_df['ConvertedCompYearly'].notna()]
result = python_df.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median']).reset_index()
result = result.rename(columns={
    'mean': 'AverageCompensation',
    'median': 'MedianCompensation'
})

print(result)

                                  Country  AverageCompensation  \
0                             Afghanistan         22328.666667
1                                 Albania         47217.600000
2                                 Algeria         20187.285714
3                                 Andorra        226103.500000
4                     Antigua and Barbuda             1.000000
..                                    ...                  ...
148  Venezuela, Bolivarian Republic of...          9908.647059
149                              Viet Nam        218837.166667
150                                 Yemen         32929.500000
151                                Zambia          5424.250000
152                              Zimbabwe         34000.000000

     MedianCompensation
0                1000.0
1               50000.0
2                7088.0
3              226103.5
4                   1.0
..                  ...
148              3000.0
149              8254.0
150             23672.0
151              3206.0
152             25500.0

[153 rows x 3 columns]

In [17]:
#Tasck 8
salary = df[df['ConvertedCompYearly'].notna()]
sort = salary.sort_values(by='ConvertedCompYearly', ascending=False)
top5 = sort.head(5)
result = top5[['EdLevel', 'ConvertedCompYearly']]
print(result)

                                               EdLevel  ConvertedCompYearly
34267              Associate degree (A.A., A.S., etc.)           50000000.0
28700  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)           33552715.0
43143              Associate degree (A.A., A.S., etc.)           18387548.0
35353     Bachelor’s degree (B.A., B.S., B.Eng., etc.)           15430267.0
45971  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)           13921760.0

In [18]:
#Tasck 9
df['Age'].unique()

array(['25-34 years old', '35-44 years old', '45-54 years old',
       '18-24 years old', '65 years or older', '55-64 years old',
       'Prefer not to say'], dtype=object)

In [20]:
#Создадим флаг Python-разработчика
df['is_python'] = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)

result = df.groupby('Age')['is_python'].mean().reset_index()
result['PythonPercent'] = result['is_python'] * 100
result = result[['Age', 'PythonPercent']]
result = result.round(2)
print(result)

                 Age  PythonPercent
0    18-24 years old          40.00
1    25-34 years old          36.94
2    35-44 years old          36.72
3    45-54 years old          38.63
4    55-64 years old          37.24
5  65 years or older          31.63
6  Prefer not to say          31.22

In [21]:
#Tasck 10
salary = df[df['ConvertedCompYearly'].notna()]
q75 = salary['ConvertedCompYearly'].quantile(0.75)
filtered = salary[(salary['ConvertedCompYearly'] > q75) &(salary['RemoteWork'] == 'Remote')]
industry_counts = filtered['Industry'].value_counts()

print(industry_counts)

Industry
Software Development                          1186
Fintech                                        190
Healthcare                                     188
Other:                                         176
Internet, Telecomm or Information Services     138
Banking/Financial Services                      88
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Computer Systems Design and Services            59
Insurance                                       46
Energy                                          45
Manufacturing                                   33
Higher Education                                30
Name: count, dtype: int64